version: 2.1
jobs:
  publish-storybook:
    docker:
      - image: circleci/node:14.5.0
    environment:
      CIRCLE_COMPARE_URL: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    steps:
      - checkout
      - run: node ./scripts/publish-storybook.js

workflows:
  publish:
    jobs:
      - publish-storybook
