version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1

commands:
  check-for-changes:
    description: "Searches for any files matching the pattern in a diff result"
    parameters:
      in:
        description: "Returns true if this pattern matches any folder/file in the diff"
        type: string
      since:
        description: "The git commit that we are checking against"
        type: string
    steps:
      - run:
          command: |
            set +e
            git diff --name-only HEAD << parameters.since >> | grep << parameters.in >>
            # Halt without failing if grep didn't find a match
            if [ $? -eq 1 ]; then
              echo "AM I RUNNING"
              circleci-agent step halt
            fi

  write-build-info:
    description: "Write relevant info to the current build/deploy to a file for referencing"
    parameters:
      data:
        description: "The contents of the build file"
        type: string
        default: |
          BUILD_COMMIT=<< pipeline.git.revision >>
      dest:
        description: "The destination of the build file"
        type: string
    steps:
      - run:
          name: "Writing build info"
          command: |
            echo "<< parameters.data >>" > << parameters.dest >>/BUILD.txt

  copy-to-s3:
    description: "Copies adirectory to a bucket (and folder) in S3"
    parameters:
      source:
        description: "The local directory to copy"
        type: string
      bucket:
        description: "The S3 bucket (and optional folder) to copy everything to"
        type: string
    steps:
      - run: aws s3 cp << parameters.source >> s3://<< parameters.bucket >> --recursive --acl public-read

jobs:
  needs-to-publish-storybook:
    docker:
      - image: circleci/node:14.5.0
    parameters:
      doc_site:
        type: string
        description: "The domain for the doc site containing the build file"
    steps:
      - checkout
      - run:
          name: "Get last published commit"
          command: |
            echo "export LAST_PUBLISHED_COMMIT=$(curl -s -f https://<< parameters.doc_site >>/storybook/BUILD.txt | sed -r 's/^.*=(.*)$/\1/')" >> $BASH_ENV
            source $BASH_ENV
      - check-for-changes:
          in: "formation-react"
          since: $LAST_PUBLISHED_COMMIT

  publish-storybook:
    executor: aws-cli/default
    environment:
      AWS_DEFAULT_REGION: us-gov-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run: yarn install
      - run:
          name: "Build Storybook"
          command: cd packages/formation-react && yarn build-storybook
      - write-build-info:
          dest: "packages/formation-react/storybook-static"
      - copy-to-s3:
          source: "./packages/formation-react/storybook-static"
          bucket: "dev-design.va.gov/storybook"

workflows:
  publish-dev:
    jobs:
      - needs-to-publish-storybook:
          doc_site: dev-design.va.gov
      - publish-storybook:
          # requires:
          #   - needs-to-publish-storybook
          context:
            - Platform
