version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1

commands:
  check-for-changes:
    description: "Searches for any files matching the pattern in a diff result"
    parameters:
      in:
        description: "Returns true if this pattern matches any folder/file in the diff"
        type: string
      since:
        description: "The git commit that we are checking against"
        type: string
    steps:
      - run: git diff --name-only HEAD << parameters.since >> | grep << parameters.in >>

  write-build-info:
    description: "Write relevant info to the current build/deploy to a file for referencing"
    parameters:
      data:
        description: "The contents of the build file"
        type: string
        default: |
          BUILD_COMMIT=<< pipeline.git.revision >>
      dest:
        description: "The destination of the build file"
        type: string
    steps:
      - run:
          name: "Writing build info"
          command: |
            echo "<< parameters.data >>" > << parameters.dest >>/BUILD.txt

jobs:
  needs-to-publish-storybook:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: "Get last published commit"
          # Eventually this will be fetching some value from a BUILD.txt file on s3
          command: |
            echo "export LAST_PUBLISHED_COMMIT=$(curl -s https://dev-design.va.gov/storybook/BUILD.txt | sed 's/^.*=\\(.*\\)$/\\1/')" >> $BASH_ENV
            source $BASH_ENV
      - check-for-changes:
          in: "formation-react"
          since: $LAST_PUBLISHED_COMMIT

  publish-storybook:
    executor: aws-cli/default
    environment:
      AWS_DEFAULT_REGION: us-gov-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run: yarn install
      - run:
          name: "Build Storybook"
          command: cd packages/formation-react && yarn build-storybook
      - write-build-info:
          dest: "packages/formation-react/storybook-static"
      - run:
          name: "Publish storybook"
          command: cd packages/formation-react && aws s3 cp ./storybook-static/ s3://dev-design.va.gov/storybook --recursive --acl public-read

workflows:
  publish:
    jobs:
      - needs-to-publish-storybook
      - publish-storybook:
          # requires:
          #   - needs-to-publish-storybook
          context:
            - Platform
